version: "3"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./api:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
    volumes:
      - ./frontend:/app
